### ISSUE TITLE
Labels for additional rounds

### ISSUE THREAD

**Issue by alexweber** [clux/duel-names#4]
In both the new Portuguese https://github.com/clux/duel-names/blob/master/portuguese.js#L19 and Spanish translations I've added an extra line assuming it would work that way, however it doesn't...

Would that be possible?  I know most latin languages have a special name for "Round of 16" so the generic "Round of X" would start at 32 instead.

**Comment by clux** [comment]
You're right. Not quite sure why, but I [hardcoded the max indices](https://github.com/clux/duel-names/blob/6fc06be59380a25270abe461757a1073679b1999/duel_names.js#L6). And in line 14.

You CAN get around it by having some extra logic in your element, but it would be nicer if the main file just looked at the size of the array passed in, and when near the limit, started delegating to these.

**Comment by alexweber** [comment]
@clux So the weird thing is I did notice that and tried replacing the `4` with `names.single.length` and it does seem to work, but it breaks another test but I couldn't nail why exactly.

**Comment by clux** [comment]
Hm. Want the last element to be the catch-all, maybe it's an off by one: `.length - 1` ?

**Comment by alexweber** [comment]
Fixed https://github.com/clux/duel-names/commit/9b8842940ca3a515939d4535a0a304a85e6ddf90

**Comment by clux** [comment]
All landed in duel-names@1.2.0
